20190917_054152 (autopush)

diff --git a/netconn b/netconn
--- a/netconn
+++ b/netconn
@@ -2,17 +2,19 @@
 #
 ##
 ###             _
-###  _ __   ___| |_ ___ ___  _ __  _ __  _ __
-### | '_ \ / _ \ __/ __/ _ \| '_ \| '_ \| '__|
-### | | | |  __/ || (_| (_) | | | | | | | |
-### |_| |_|\___|\__\___\___/|_| |_|_| |_|_|
+###  _ __   ___| |_ ___ ___  _ __  _ __
+### | '_ \ / _ \ __/ __/ _ \| '_ \| '_ \
+### | | | |  __/ || (_| (_) | | | | | | |
+### |_| |_|\___|\__\___\___/|_| |_|_| |_|
 ###
 ###  _ _|_ _ ._    _  _
 ### (_\/|_(_)|_)\/(_|(/_
 ###   /      |  /  _|
 ###
-### netconnr
+### netconn
 ### connect to a network
+###
+### usage: netconn [-w <config.wifi>]
 ###
 ### (c) 2019 cytopyge
 ###
@@ -31,20 +33,25 @@ NOC='\033[0m' # no color
 
 # read_flags
 
-while getopts ":w:" opt; do
+while getopts ":w:h" opt; do
 	case $opt in
 		w)
 			## -w wireless network flag
 			w=${OPTARG}
 			wl_conf="$HOME/keys_/wl/$w.wifi"
 			;;
+		h)
+			## -h display help text
+			printf "netconn: usage: netconn [-w <config.wifi>]\n"
+			exit 0
+			;;
 		\?)
-			printf "${RED}invalid option: -${OPTARG}${NOC}"
+			printf "netconn: ${RED}invalid option: -${OPTARG}${NOC}"
 			exit 1
 			;;
 		:)
-			# display help
-			printf "${RED}option -${OPTARG} requires an argument${NOC}"
+			## display help
+			printf "netconn: ${RED}option -${OPTARG} requires an argument${NOC}"
 			exit 1
 			;;
 	esac
@@ -83,6 +90,8 @@ reply_single_hidden() {
 }
 
 
+# ##
+
 get_sudo() {
 
 	sudo -k
@@ -106,10 +115,10 @@ select_interface() {
 	## derive interface from interface_number
 	interface=$(ip a | grep "^$interface_number" | awk '{print $2}' | sed 's/://')
 
-	## if interface is wireless, check for valid option
+	## if interface is wireless, check for entered wireless network flag
 	if [ ${interface:0:1} == 'w' ] && [ -z $wl_conf ]; then
 		echo
-		printf "${RED}no configuration allocated for interface '$interface'${NOC}\n"
+		printf "${RED}no wireless configuration allocated for '$interface'${NOC}\n"
 		printf "exiting...\n"
 		exit
 	fi
