20230303_110014 (update_mon)

diff --git a/netkill b/netkill
--- a/netkill
+++ b/netkill
@@ -11,7 +11,7 @@
 ###
 ### netkill
 ### thoroughly kill a network connection
-### (c) 2019 - 2021  |  oxo
+### copyright (c) 2019 - 2023  |  oxo
 ###
 ##
 #
@@ -19,13 +19,13 @@
 
 # script specific constants
 
-script_name="netkill"
-developer="oxo"
-initial_release_year=2019
+script_name='netkill'
+developer='oxo'
+initial_release_year='2019'
 source_dir="$XDG_DATA_HOME/c/git/code/source/function"
 temp_dir="$XDG_CACHE_HOME/temp"
 
-source_ip="9.9.9.9"
+source_ip='9.9.9.9'
 netistat="$XDG_DATA_HOME/c/git/code/tool/netistat"
 
 # general function definitions
@@ -58,7 +58,8 @@ permission()
 temp_dir()
 {
 	[[ -d $temp_dir ]] || mkdir -pv $temp_dir
-	t0=`date +%Y%m%d_%H%M%S`
+	t0=$(date +%Y%m%d_%H%M%S)
+	#t0=`date +%Y%m%d_%H%M%S`
 	ip a > $temp_dir/"$t0"_netkill.tmp
 }
 
@@ -211,7 +212,8 @@ get_interface()
 
 	if [[ -z $i ]]; then
 
-		exit
+	    printf 'could not get interface\n'
+		exit 216
 
 	fi
 }
